#!/bin/bash

apt-get update
apt-get --assume-yes install build-essential ruby1.8 ruby1.8-dev libopenssl-ruby1.8 rdoc1.8 ri1.8 irb1.8 ssl-cert wget

ln -sfv /usr/bin/ruby1.8 /usr/bin/ruby
ln -sfv /usr/bin/ri1.8 /usr/bin/ri
#ln -s /usr/bin/rdoc1.8 /usr/bin/rdoc
ln -sfv /usr/bin/irb1.8 /usr/bin/irb

wget http://production.cf.rubygems.org/rubygems/rubygems-1.3.7.tgz  
tar xzf rubygems-1.3.7.tgz
cd rubygems-1.3.7
ruby setup.rb --no-format-executable
cd ..
rm rubygems-1.3.7.tgz
rm -r rubygems-1.3.7

ln -sfv /usr/bin/gem1.8 /usr/bin/gem

gem update --system
gem install chef
