#!/bin/bash

apt-get update
apt-get --assume-yes install build-essential ruby ruby1.8-dev libopenssl-ruby1.8 rdoc ri irb ssl-cert wget

wget http://rubyforge.org/frs/download.php/69365/rubygems-1.3.6.tgz  
tar xzvf rubygems-1.3.6.tgz
cd rubygems-1.3.6
ruby setup.rb
cd ..
rm rubygems-1.3.6.tgz
rm -r rubygems-1.3.6
ln -sfv /usr/bin/gem1.8 /usr/bin/gem
ln -sfv /usr/bin/ri1.8 /usr/bin/ri
#ln -s /usr/bin/rdoc1.8 /usr/bin/rdoc
ln -sfv /usr/bin/irb1.8 /usr/bin/irb
gem update --system
#gem sources -a http://gems.opscode.com
#gem install ohai chef --no-ri --no-rdoc
gem install chef
