#!/bin/bash

RUBY="ruby-1.9.2-p290"
YAML="yaml-0.1.4"

sudo apt-get update
sudo apt-get --assume-yes install build-essential zlib1g zlib1g-dev libreadline6 libreadline6-dev libssl-dev wget


if [ ! -d /tmp/src ]; then
	mkdir /tmp/src
fi

#cd /tmp/src
#wget http://pyyaml.org/download/libyaml/$YAML.tar.gz
#tar xvfz $YAML.tar.gz
#cd $YAML
#./configure --prefix=/usr/local/bin/$RUBY
#make
#make install
#
cd /tmp/src
wget ftp://ftp.ruby-lang.org/pub/ruby/1.9/$RUBY.tar.gz
tar -zxvf $RUBY.tar.gz && cd $RUBY
./configure --prefix=/usr
make
sudo make install
sudo gem update --system
sudo gem install ohai
sudo gem install chef
